### ISSUE TITLE
PCF Architect vs Operator

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/docs-pcf-gsg#11]
The differentiation between a PCF Architect and Operator runs counter to what we are teaching our customers how to think about their teams. (in docs-pcf-gsg/index.html.md.erb)

Our goal is to train up a Platform team for the customers which will be staffed with Platform Engineers and Platform Product Managers. They will be responsible for designing, operating, and enhancing the Platform. There is no ops vs. architect; this is not a DevOps best practice.

We should probably remove this section for now, which explains the differentiation of roles. We can then review with @joefitzgerald and team later.

**Comment by ryanpei** [comment]
I see that this has PCF Operator vs. PCF Administrator vs. PCF Architect differentiation has been incorporated into the entire set of documentation.

How were these activities allocated per role? Was this based on polling of customers?

Would it be better to separate these activities into categories per sets of concepts or technologies that the Platform team would be involved with? E.g. Networking, PAS, Ops Manager, PAS for Windows, etc., and then at the highest level, "Platform Overview", which would cover the Reference Architecture?

**Comment by pspinrad** [comment]
@ryanpei for sure, yes, let's discuss!  We have generally heard that people want our docs to be more role-based, with clearer differentiations by role.

**Comment by pspinrad** [comment]
Hopefully it doesn't have to conflict with how platform teams are organized. Framing "roles" is different from assigning these categories to actual people on a team with different titles, and team members can serve different roles.

F'rinstance, a platform PM or platform engineer can act as the architect who designs the installation, the operator who installs and configures it, etc.

**Comment by johnpfield** [comment]
+1 to "roles" versus "job titles."  

It may be helpful to get some PA’s involved in helping to shape the language / message.   Many of the PA's I've worked with at customer sites suggest that there are at least 4 distinct operational roles involved in the enterprise teams that run PCF deployments (and usually more).  Our PA team likely has some good advice on how the devops approach is realized in terms of roles/functions at their/our customers.

**Comment by joefitzgerald** [comment]
@johnpfield, It is extremely confusing to talk about roles when we are advocating to customers that we build balanced platform product teams that share the various roles. The temptation when looking at a list of roles is to assume that each role is filled by a different person. In reality, it often is not.

The plan / build / run culture at many of our customers is ingrained and well established. When we talk to the roles in this way, we are skating to where the puck is rather than where it will be. I agree with Ryan's comments.

**Comment by pspinrad** [comment]
+1 to making it clear that role does not equal person, and that teams share roles -- although the roles in docs do mirror the "personas" here: https://pcf.aha.io/products/PCF/personas/

**Comment by ryanpei** [comment]
It sounds like we still disagree. As Joe said, roles vs. persons is not distinguishable in the eyes of most enterprise customers. Should we have a meeting to discuss this further?

**Comment by pspinrad** [comment]
For sure-- let's definitely discuss, will be great to figure out.  Wanna schedule something, or should I?

Thanks, and thanks also for suggestions about moving things around— like explaining that setting up LB’s and user accounts are Day 1, not Day 2-- very helpful!

**Comment by pspinrad** [comment]
More thoughts-- just posted same to c0 Slack thread:

I do want to incorporate terms from the dojos, Platform Team concepts, into the top-level framing of the docs, so new users know they're in the right place and that as a company we have a consistent voice-- rather than their coming to the docs and going, whaaat? I'm all for cross-team alignment on terminology and concepts.

Is the person who designs the PCF platform, consider its needs, capacity, budget, etc, (what we currently call "Architect"), is that the Platform Project Manager?  If so, I'm totally down with doing that string-substitution.

What a PCF user can do with PCF, and therefore which docs are relevant to them, are determined by things like whether they have an account in the Ops Manager UAA, or have `cloud_controller.admin` scope in the PAS UAA. So I'd love to come up with some intuitive and non-distracting terms to distinguish these users, whether we call them roles, permissions, personas, privileges, etc., in a way that fits it in with and is informed by the Platform Team concepts.

**Comment by johnpfield** [comment]
@joefitzgerald I don't think there is any disagreement....  I'm just saying "+1 to roles." I don't have a strong opinion on what those roles should be called.  I'm also not suggesting that we be prescriptive about how those roles should be associated to specific people or jobs. But I'm pretty sure "role" is the right word here, as it has exactly the correct meaning in both a technical sense (e.g. as in NIST RBAC) and also in [common usage](https://www.google.com/search?q=Dictionary#dobs=role). 

@ryanpei Point taken.  In my experience customers have been fine with the concept of "role."  I've actually not come across any situations where role was confused as synonymous with "persona" or "person," but hey, it could certainly happen.  I'm sure @pspinrad can help us make it all clear.  

And +1 to ice hockey analogies.  Having played ice hockey for a number of years, I appreciate the need to skate to where the puck will be. 👍

**Comment by mlimonczenko** [comment]
Hello,

This thread is several years old and so I am closing it out.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

Thank you so much for your contribution.
